### ISSUE TITLE
yo thinkphp新建项目问题

### ISSUE THREAD

**Issue by JimChenWYU** [discountry/generator-thinkphp#3]
平台：win10
shell：git-bash

在桌面执行`yo thinkphp`，命名项目名假设是app后，生成目录结构也是
app
----app
-------Application
-------Public
-------省略
----.yo-rc.json

我的问题就是产生项目目录结构时为什么会多出一层的目录结构？

**Comment by discountry** [comment]
我手动修改了ThinkPHP的目录结构，模仿laravel的目录编排。
这个项目已经很久没跟进过了，感谢你的关注。
